version: '3.8'

services:
  api:
    build:
      context: ./
    container_name: api
    command: sh -c "chmod +x wait_for_postgres.sh && ./wait_for_postgres.sh && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app # Any changes made to files or directories within the text_summarization directory on the host machine will be reflected inside the container at /usr/src/app.
    ports:
      - 8004:8000 # Any traffic sent to port 8004 on the host will be forwarded to port 8000 within the container where the service is listening. => http://localhost:8004/docs
    env_file:
      - .env